name: chips_auto_scroll_example
description: Example app demonstrating the chips_auto_scroll package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  chips_auto_scroll:
    path: ../

flutter:
  uses-material-design: true
